apiVersion: v1
kind: Service
metadata:
  name: nestjs-api-svc
  namespace: beta
spec:
  selector:
    app: nestjs-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 14000
      targetPort: 4000
      nodePort: 30004 # this is for when using type: NodePort
